model_name: "microsoft/deberta-v3-base"
batch_size: 64
lr: 1e-3
epochs: 10
weight_decay: 0.01
lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules: ["query_proj","key_proj","value_proj","output_proj"]  # adjust per model
output_dir: "artifacts/models/deberta_lora"
